[versions]
gradlePlugin = "7.3.1"
kotlin = "1.7.0"
nexusPublish = "1.1.0"
nexusStaging = "0.22.0"

[libraries]

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
nexus-publish = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexusPublish" }
nexus-staging = { module = "io.codearte.gradle.nexus:gradle-nexus-staging-plugin", version.ref = "nexusStaging" }
