name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build project
        run: ./gradlew assembleDebug

  test:
    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
    strategy:
      matrix:
        api-level: [ 26, 31 ]
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run instrumentation tests
        uses: ReactiveCircus/android-emulator-runner@v2.21.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: pixel_2
          disable-animations: true
          script: ./gradlew :sample:connectedCheck
