name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - uses: ReactiveCircus/android-emulator-runner@v1.0.2
      name: Run tests
      with:
        api-level: 29
        headless: true
        disable-animations: true
        script: ./gradlew connectedCheck

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-
